[local]
localhost

[mongodb]
mongodb-dev.pmpkdev.online

[catalogue]
catalogue-dev.pmpkdev.online

[redis]
redis-dev.pmpkdev.online

[cart]
cart-dev.pmpkdev.online

[user]
user-dev.pmpkdev.online

[mysql]
mysql-dev.pmpkdev.online

[shipping]
shipping-dev.pmpkdev.online