- name: ansible roles
  hosts: local
  connection: local
  vars:
    topic: vault from play
  roles:
  - demo  # When Ansible executes, it looks for the demo role inside the roles directory and loads it.
          # Instead of keeping everything in a single playbook, the demo role organizes different components into separate directories, making the code modular, reusable, and easier to maintain.